### ISSUE TITLE
Redirect list is not loading - Errors in Dev Console

### ISSUE THREAD

**Issue by benediktgrether** [neos/redirecthandler-ui#86]
Hi, 

we run in some Issues. 
The redirect list is not loading. And we got some Error Messages in the console. 

Console from Chrome

```
bootstrap.min.js:6 Uncaught TypeError: e is not a function
    at bootstrap.min.js:6:27
    at bootstrap.min.js:6:352
(anonymous) @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6
fixedsticky.js:185 Uncaught ReferenceError: jQuery is not defined
    at fixedsticky.js:185:11
(anonymous) @ fixedsticky.js:185
redirects:316 Uncaught ReferenceError: jQuery is not defined
    at redirects:316:7
(anonymous) @ redirects:316
ContentModule-built.js?bust=e93a454378f6:428 Uncaught TypeError: Cannot read properties of undefined (reading 'requirejs')
    at ContentModule-built.js?bust=e93a454378f6:428:1137619
(anonymous) @ ContentModule-built.js?bust=e93a454378f6:428
redirects:325 Uncaught ReferenceError: $ is not defined
    at redirects:325:4
``` 

And Console from Firefox
```
Uncaught TypeError: e is not a function
    <anonymous> https://www.basel.com/_Resources/Static/Packages/Neos.Twitter.Bootstrap/2/js/bootstrap.min.js:6
    <anonymous> https://www.basel.com/_Resources/Static/Packages/Neos.Twitter.Bootstrap/2/js/bootstrap.min.js:6
[bootstrap.min.js:6:28](https://www.basel.com/_Resources/Static/Packages/Neos.Twitter.Bootstrap/2/js/bootstrap.min.js)
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://www.basel.com/_Resources/Static/Packages/Neos.Neos/Library/fixedsticky/fixedsticky.js:14
[fixedsticky.js:14:1](https://www.basel.com/_Resources/Static/Packages/Neos.Neos/Library/fixedsticky/fixedsticky.js)
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://www.basel.com/neos/management/redirects:316
[redirects:316:1](https://www.basel.com/neos/management/redirects)
Uncaught TypeError: window.T3Configuration is undefined
    <anonymous> https://www.basel.com/_Resources/Static/Packages/Neos.Neos/JavaScript/ContentModule-built.js?bust=e93a454378f6:53
ContentModule-built.js:53:1137616
Uncaught ReferenceError: $ is not defined
    <anonymous> https://www.basel.com/neos/management/redirects:325
```

We use 
```
 Neos.Neos                                 4.3.19 
 Neos.RedirectHandler                      3.0.3          
 Neos.RedirectHandler.DatabaseStorage      4.1.0          
 Neos.RedirectHandler.NeosAdapter          4.3.0          
 Neos.RedirectHandler.Ui                   2.4.4
```

A few weeks ago i had the same issue. I can fix it with this workaround
1. Export all redirects.
2. Remove all redirects over console.
3. Add all redirects in neos backend. 
4. Some redirects where marked in orange. 
5. I delete the orange marked redirects and everthing run fine again. 

But this time. This Workaround is not working. 

Do you have any Ideas?

**Comment by benediktgrether** [comment]
Hi Sebobo,
thank you. I updated the packages to 2.4.6 and everything work fine now. 
I think i was on the highest Version 🤦 .
